# The picker. sesh lists tmuxinator projects alongside live tmux sessions and
# zoxide's frecent directories, and `connect -T` starts a project through
# tmuxinator when it isn't already running -- so a session costs nothing until
# it is chosen, and choosing it is the same keystroke either way.
{ config, pkgs, ... }:
{
  home.packages = [ pkgs.sesh ];

  # `sesh list -T` reads these straight off disk, so the projects rendered by
  # the tmuxinator module show up in the picker with no duplication here.
  xdg.configFile."sesh/sesh.toml".text = ''
    # Generated by nix -- edit modules/home/terminal/sesh, not this file.

    [default_session]
    startup_command = "clear"

    # Session 0 is the throwaway tmux creates when a server starts with no
    # target; it is never worth picking.
    blacklist = ["0"]
  '';

  programs.tmux.extraConfig = ''
    # o -- session picker. -T lists tmuxinator projects; connect -T starts the
    # chosen one through tmuxinator if no such session exists yet.
    bind-key -N "Pick a session" o run-shell -b "${pkgs.sesh}/bin/sesh connect -T \"$(${pkgs.sesh}/bin/sesh list -T -t -z -i -H | ${pkgs.fzf}/bin/fzf-tmux -p 80%,70% --no-sort --ansi --prompt='session> ')\""

    # C-o -- jump back to the previous session. (Plain L is next-window in
    # tmux.reset.conf, and o/C-o only shadow tmux's default select-pane.)
    bind-key -N "Last session" C-o run-shell "${pkgs.sesh}/bin/sesh last"
  '';
}
