# Autocomplete
bindkey '^w' autosuggest-execute
bindkey '^e' autosuggest-accept
bindkey '^u' autosuggest-toggle
bindkey '^L' vi-forward-word
bindkey '^k' up-line-or-search
bindkey '^j' down-line-or-search

# Homebrew
if [[ $(uname) == 'Darwin' ]]; then
  # Homebrew
    export PATH="/opt/homebrew/bin:$PATH"
    export PATH="/opt/homebrew/sbin:$PATH"
    eval "$(/opt/homebrew/bin/brew shellenv)"

    # Draw.io cli
    alias drawio="/Applications/draw.io.app/Contents/MacOS/draw.io"
fi

# Rust builds
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
export CC=/opt/homebrew/opt/llvm/bin/clang
export AR=/opt/homebrew/opt/llvm/bin/llvm-ar

# AWS
alias awsp="source _awsp"

# Startship
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

# Git cliff
export GIT_CLIFF_CONFIG="$HOME/.config/git-cliff/cliff.toml"

# FZF
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow'

# Prettierd
export PRETTIERD_DEFAULT_CONFIG="$HOME/.config/prettierd/default.json"
