# Session layouts, declared once and rendered to tmuxinator projects.
#
# This is the lazy half of the session setup: nothing here starts a session or
# holds a process. A project is an inert YAML file until `sesh connect -T` (or
# `tmuxinator start <key>`) materialises it, which is the whole point -- the old
# resurrect/continuum arrangement respawned every pane of every session at
# server start, 36 idle shells at ~5 MB each whether or not they were wanted.
#
# `dotfiles.sessions` is the single source of truth. Shared projects live here;
# machine-specific ones are added by profile/{personal,work}.nix, so the work
# mac never renders a project for a repo it does not have checked out.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.dotfiles.sessions;

  # YAML needs quoting for the paths with spaces in them (the MSc tree), and
  # quoting unconditionally is cheaper than deciding when it matters.
  q = s: ''"${s}"'';

  windowType = lib.types.submodule {
    options = {
      name = lib.mkOption {
        type = lib.types.str;
        description = "tmux window name.";
      };
      root = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Window working directory. Defaults to the session root.";
      };
      layout = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "tmux layout preset, e.g. main-vertical or even-horizontal.";
      };
      panes = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ "." ];
        description = ''
          One entry per pane. "." is a plain shell in the window root; any other
          value is treated as a path relative to it and entered with `cd`.
        '';
      };
    };
  };

  sessionType = lib.types.submodule {
    options = {
      root = lib.mkOption {
        type = lib.types.str;
        description = "Session root directory.";
      };
      windows = lib.mkOption {
        type = lib.types.listOf windowType;
        description = "Windows, in order.";
      };
    };
  };

  # A quoted "~" is a literal tilde to the shell, so rewrite a leading ~/ to
  # $HOME/ -- that survives quoting, which the paths with spaces in them need.
  shellPath = p: q (if lib.hasPrefix "~/" p then "$HOME/" + lib.removePrefix "~/" p else p);

  mkPane = root: p: if p == "." then "        -" else "        - cd ${shellPath p}";

  mkWindow =
    w:
    let
      plain = w.panes == [ "." ] && w.layout == null && w.root == null;
    in
    if plain then
      "  - ${w.name}:"
    else
      lib.concatStringsSep "\n" (
        [ "  - ${w.name}:" ]
        ++ lib.optional (w.root != null) "      root: ${q w.root}"
        ++ lib.optional (w.layout != null) "      layout: ${q w.layout}"
        ++ [ "      panes:" ]
        ++ map (mkPane w.root) w.panes
      );

  # `sesh connect -T` looks the project up by the session name, so the tmuxinator
  # `name:` and the filename have to agree exactly -- when they differ sesh finds
  # no match, silently does nothing and still exits 0. Deriving both from the
  # attribute key makes that mismatch unrepresentable.
  mkProject = key: s: ''
    # Generated by nix -- edit modules/home/terminal/tmuxinator, not this file.
    name: ${q key}
    root: ${q s.root}

    windows:
    ${lib.concatStringsSep "\n" (map mkWindow s.windows)}
  '';
in
{
  options.dotfiles.sessions = lib.mkOption {
    type = lib.types.attrsOf sessionType;
    default = { };
    description = "Named tmux session layouts, rendered to ~/.config/tmuxinator.";
  };

  config = {
    home.packages = [ pkgs.tmuxinator ];

    # Projects every machine has a checkout of.
    dotfiles.sessions."Dotfiles" = {
      root = "~/dotfiles";
      windows = [
        { name = "editor"; }
        {
          name = "dev";
          layout = "even-horizontal";
          panes = [
            "."
            "."
          ];
        }
        { name = "shell"; }
      ];
    };

    xdg.configFile = lib.mapAttrs' (
      key: s: lib.nameValuePair "tmuxinator/${key}.yml" { text = mkProject key s; }
    ) cfg;
  };
}
